name: unity-catalog-tpch

services:
  unitycatalog:
    image: unitycatalog/unitycatalog:0.6.0-SNAPSHOT
    hostname: unitycatalog
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./server.properties
        target: /home/unitycatalog/etc/conf/server.properties
        read_only: true
    healthcheck:
      test:
        - CMD-SHELL
        - "wget -q -O /dev/null http://localhost:8080/api/2.1/unity-catalog/catalogs || exit 1"
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 20s
