/// <reference types="vite/client" />
/// <reference types="likec4/vite-plugin-modules" />

// Drafts are Markdown loaded through @mdx-js/rollup, so they resolve as React
// component modules.
declare module "*.md" {
  import type { ComponentType } from "react";
  export const frontmatter: Record<string, unknown>;
  const MDXComponent: ComponentType;
  export default MDXComponent;
}
declare module "*.mdx" {
  import type { ComponentType } from "react";
  export const frontmatter: Record<string, unknown>;
  const MDXComponent: ComponentType;
  export default MDXComponent;
}

// The LikeC4 model is generated by `likec4 codegen react` before dev/build.
// A checked-in stub keeps types resolving before the first codegen; the real
// file overwrites it and is gitignored.
declare module "@/likec4.generated" {
  import type { ComponentType } from "react";
  export const LikeC4View: ComponentType<{ viewId: string }>;
}

// The estate architecture model (../architecture/model) is served by the LikeC4
// Vite plugin as virtual modules (likec4:react, likec4:single-project, …). Their
// types come from the `likec4/vite-plugin-modules` reference at the top of this
// file; no local stub or codegen'd file is needed.
